name: orchestrator-deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  Linux:
    runs-on: [self-hosted, orchestrator]
    steps:
    - name: Cycle VMs
      shell: bash
      env:
        XOA_URL: ${{ secrets.XOA_URL }}
        XOA_USER: ${{ secrets.XOA_USER }}
        XOA_PASSWORD: ${{ secrets.XOA_PASSWORD }}
      run: |
        pushd ~
        ruby ./main.rb
        ruby ./linux.rb
        terraform apply # --auto-approve -- not while testing